fundraiser/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from .views import IndexView
from team_fundraising.admin import DonorCsv


urlpatterns = [
    path('', IndexView.as_view()),
    path('team_fundraising/', include('team_fundraising.urls')),

    # Donation reports in the admin section
    path(
        'admin/donation_report_csv/<int:campaign_id>/',
        staff_member_required(DonorCsv.as_view()),
        name="donation_report_csv"
    ),
    path('admin/', admin.site.urls),

    # Had to add accounts here as well, as internal functions call it without
    # a namespace
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

team_fundraising/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views
from .views import Paypal_donation, About, OneClickSignUp

app_name = 'team_fundraising'

urlpatterns = [
    path('', views.index_view_default, name='index_default'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('<campaign_id>/', views.index_view, name='index'),
    path(
        'fundraiser/<int:fundraiser_id>/',
        views.fundraiser_view,
        name='fundraiser'
    ),
    path('donation/<int:fundraiser_id>/', views.new_donation, name="donation"),
    path('paypal_donation/<int:fundraiser_id>/', Paypal_donation.as_view()),
    path(
        'accounts/update_fundraiser/',
        views.update_fundraiser,
        name="update_fundraiser",
    ),
    path(
        'accounts/update_fundraiser/<int:campaign_id>/',
        views.update_fundraiser,
        name="update_fundraiser",
    ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/<int:campaign_id>/', views.signup, name="signup"),
    path(
        'accounts/signup_logged_in/<int:campaign_id>/',
        login_required(OneClickSignUp.as_view()),
        name="signup_logged_in"
    ),
    path(
        'accounts/change_password/',
        views.change_password,
        name='change_password'
    ),
    path('about/<int:campaign_id>/', About.as_view(), name="about"),
]

team_fundraising/forms.py
""" The forms for the team_fundraiser app
"""
from django import forms
from django.utils import timezone
from .models import Fundraiser
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class DonationForm(forms.Form):
    """ Form for a new Donation, which can be tied to a specific fundraiser """

    name = forms.CharField()
    amount = forms.CharField()
    other_amount = forms.CharField(required=False)
    email = forms.EmailField()
    anonymous = forms.BooleanField(required=False)
    tax_name = forms.CharField(label='Full Name', required=False)
    address = forms.CharField(max_length=100, required=False)
    city = forms.CharField(max_length=50, required=False)
    province = forms.CharField(max_length=50, required=False)
    country = forms.CharField(max_length=25, required=False)
    postal_code = forms.CharField(max_length=10, required=False)
    date = timezone.now()

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'required': False, 'rows': 3}
        ),
        required=False
    )

    def clean(self):
        # if the user chooses "other amount", make that the amount

        cleaned_data = super().clean()

        try:
            amount = cleaned_data.get("amount")
        except KeyError:
            amount = ""

        try:
            other_amount = cleaned_data.get("other_amount")
        except KeyError:
            other_amount = ""

        if amount == 'other' or amount == '':
            # TODO pull out just the number, in case they added a $
            try:
                cleaned_data['amount'] = float(other_amount)
            except ValueError:
                raise forms.ValidationError("Amount is not a number")

        return cleaned_data


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):

        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.pop("autofocus", None)

        self.fields['email'].required = True
        self.fields['username'].required = True

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]
        user.is_staff = False
        user.is_admin = False

        if commit:
            user.save()

        return user


class FundraiserForm(forms.ModelForm):
    class Meta:
        model = Fundraiser
        fields = ('campaign', 'name', 'goal', 'photo', 'message')
        widgets = {
            'campaign': forms.HiddenInput(),
            'message': forms.Textarea(attrs={'rows': 3, 'cols': 20}),
        }

    def __init__(self, *args, **kwargs):
        super(FundraiserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['name'].widget.attrs['size'] = 50
        self.fields['goal'].widget.attrs['size'] = 10

        self.fields['name'].required = True
        self.fields['goal'].required = True

        # disable all the fields if the campaign is no longer active
        if self.instance.pk is not None:

            if self.instance.campaign.active is False:

                for field in self.fields:
                    self.fields[field].disabled = True

team_fundraising/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.mail import send_mail
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views import View
from paypal.standard.forms import PayPalPaymentsForm

from .models import Campaign, Fundraiser, Donation, ProxyUser
from .forms import DonationForm, UserForm, FundraiserForm, SignUpForm
from .text import Donation_text, Fundraiser_text


def index_view(request, campaign_id):
    # The home page, shows all fundraisers and total raised

    template = 'team_fundraising/index.html'

    campaign = get_object_or_404(Campaign, pk=campaign_id)

    fundraisers = campaign.get_fundraisers_with_totals()

    # get 5 recent "paid" donations by newest date
    recent_donations = campaign.get_recent_donations(5)

    # get raised by fundraisers and add general donations
    total_raised = campaign.get_total_raised()

    context = {
        'campaign': campaign,
        'fundraisers': fundraisers,
        'total_raised': total_raised,
        'recent_donations': recent_donations,
    }

    return render(request, template, context)


def index_view_default(request):

    campaign = Campaign.get_latest_active_campaign()

    return index_view(request, campaign.id)


def fundraiser_view(request, fundraiser_id):
    # An individual's fundraising page, including total and donations

    template = 'team_fundraising/fundraiser.html'

    fundraiser = get_object_or_404(Fundraiser, pk=fundraiser_id)
    campaign = get_object_or_404(Campaign, pk=fundraiser.campaign_id)

    fundraiser.total_raised = fundraiser.total_raised()

    if fundraiser.goal != 0:
        fundraiser.percent_raised = int(
            fundraiser.total_raised) / fundraiser.goal * 100

    donations = fundraiser.donation_set.filter(
        payment_status__in=["paid", ""]).order_by('-date')

    context = {
        'campaign': campaign,
        'fundraiser': fundraiser,
        'donations': donations,
    }

    return render(request, template, context)


def new_donation(request, fundraiser_id):
    # Show donation page, on submit show confirmation and button to PayPal

    fundraiser = get_object_or_404(Fundraiser, pk=fundraiser_id)
    campaign = Campaign.objects.filter(fundraiser=fundraiser_id).first()

    if request.method == "POST":

        form = DonationForm(request.POST)

        if form.is_valid():

            # populate the model with form values
            donation = Donation()
            donation.fundraiser = fundraiser
            donation.name = form.cleaned_data['name']
            donation.amount = form.cleaned_data['amount']
            donation.email = form.cleaned_data['email']
            donation.anonymous = form.cleaned_data['anonymous']
            donation.message = form.cleaned_data['message']
            donation.tax_name = form.cleaned_data['tax_name']
            donation.address = form.cleaned_data['address']
            donation.city = form.cleaned_data['city']
            donation.province = form.cleaned_data['province']
            donation.country = form.cleaned_data['country']
            donation.postal_code = form.cleaned_data['postal_code']
            donation.payment_method = 'paypal'
            donation.payment_status = 'pending'
            donation.save()

            paypal_dict = {
                "bn": "TripleCrown_Donate_WPS_CA",
                "business": settings.PAYPAL_ACCOUNT,
                "amount": donation.amount,
                "currency_code": "CAD",
                "item_name": "Donation",
                "invoice": "TRIPLE_CROWN_"+str(donation.id),
                "notify_url": request.build_absolute_uri(
                    reverse('team_fundraising:paypal-ipn')
                    ),
                "return": request.build_absolute_uri(
                    reverse(
                        'team_fundraising:fundraiser', args=[fundraiser_id])
                    ),
                "cancel_return": request.build_absolute_uri(
                    reverse(
                        'team_fundraising:fundraiser', args=[fundraiser_id])
                    ),
                "custom": donation.id,
            }

            template_name = 'team_fundraising/paypal_donation.html'

            # create the instance
            form = PayPalPaymentsForm(
                initial=paypal_dict, button_type="donate")

            context = {
                "form": form,
                'donation': donation,
                'campaign': campaign,
                }

            # leave a message that the user will see on their return
            # from PayPal
            messages.add_message(
                request,
                messages.SUCCESS,
                Donation_text.thank_you
            )

            return render(request, template_name, context)

    else:

        form = DonationForm()

    template = "team_fundraising/donation.html"

    context = {
        'form': form,
        'campaign': campaign,
        'fundraiser': fundraiser,
    }

    return render(request, template, context)


class Paypal_donation(View):
    # initial test of the paypal donation - no longer used

    template_name = 'team_fundraising/paypal_donation.html'

    def get(self, request, fundraiser_id):

        paypal_dict = {
            "bn": "TripleCrown_Donate_WPS_CA",
            "business": settings.PAYPAL_ACCOUNT,
            "amount": "50.00",
            "currency_code": "CAD",
            "item_name": "Donation",
            "invoice": "unique-invoice-id",
            "notify_url": request.build_absolute_uri(
                reverse('team_fundraising:paypal-ipn')
                ),
            "return": request.build_absolute_uri(
                reverse('team_fundraising:fundraiser', args=[fundraiser_id])
                ),
            "cancel_return": request.build_absolute_uri(
                reverse('team_fundraising:fundraiser', args=[fundraiser_id])
                ),
            "custom": fundraiser_id,
        }

        # create the instance
        form = PayPalPaymentsForm(initial=paypal_dict, button_type="donate")
        context = {
            "form": form
            }

        return render(request, self.template_name, context)


def signup(request, campaign_id):
    # Create both a fundraiser and a user, tied together through a foreign key

    if request.method == "POST":

        fundraiser_form = FundraiserForm(request.POST, request.FILES)
        user_form = SignUpForm(request.POST)

        # if you are adding a fundraiser to an existing user
        if User.objects.filter(username=request.POST['username']).exists():

            if fundraiser_form.is_valid():

                if request.user.is_authenticated:

                    user = request.user

                else:

                    # check if the password is correct
                    user = authenticate(
                        request,
                        username=request.POST['username'],
                        password=request.POST['password1']
                    )

                if user is not None:

                    # check to see if there is already a fundraiser
                    # in this campaign
                    if Fundraiser.objects.filter(
                        user=user.id,
                        campaign=campaign_id,
                    ).exists():

                        login(request, user)

                        # send them to the update fundraiser page
                        return redirect('team_fundraising:update_fundraiser')

                else:

                    messages.error(
                        request,
                        Fundraiser_text.signup_wrong_password_existing_user,
                        extra_tags='safe',
                        )

                    campaign = get_object_or_404(Campaign, pk=campaign_id)

                    return render(request, 'registration/signup.html', {
                        'campaign': campaign,
                        'user_form': user_form,
                        'fundraiser_form': fundraiser_form,
                    })

        else:  # new user

            if user_form.is_valid() and fundraiser_form.is_valid():

                user = user_form.save()

        if fundraiser_form.is_valid():

            fundraiser = fundraiser_form.save()

            # tie this user to the fundraiser and save the model again
            fundraiser.user = user
            fundraiser.save()

            # send them an email that they have successfully signed up
            send_mail(
                Fundraiser_text.signup_email_subject,
                Fundraiser_text.signup_email_opening
                + request.build_absolute_uri(
                    reverse(
                        'team_fundraising:fundraiser', args=[fundraiser.id]
                    )
                )
                + "\n\nYour username is: " + user.username
                + Fundraiser_text.signup_email_closing,
                'fundraising@triplecrownforheart.ca',
                [user.email, ],
                auth_user=settings.EMAIL_HOST_USER,
                auth_password=settings.EMAIL_HOST_PASSWORD
            )
        else:  # not a valid fundraiser form

            messages.error(
                request,
                "Something went wrong. Please try again.",
                extra_tags='safe',
                )

            campaign = get_object_or_404(Campaign, pk=campaign_id)

            return render(request, 'registration/signup.html', {
                'campaign': campaign,
                'user_form': user_form,

team_fundraising/templates/base.html
{% extends "base_nonav.html" %}
{% load static %}
    {% block navbar %}
        <!-- Image and text -->
        <nav class="navbar navbar-expand navbar-light bg-light">
            <a class="navbar-brand" href="#">
                <img src="{% static "tc4h_logo.png" %}" width="40" height="40" class="d-inline-block align-top" alt="">
            </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'team_fundraising:index' campaign.id %}">Home</a>
                <a class="nav-item nav-link" href="{% url 'team_fundraising:about' campaign.id %}">About</a>

                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'team_fundraising:update_fundraiser' campaign.id %}">Edit</a>
                    <a class="nav-item nav-link" href="{% url 'team_fundraising:logout' %}?next={% url 'team_fundraising:index' campaign.id %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'team_fundraising:signup' campaign.id %}">Join</a>
                    <a class="nav-item nav-link" href="{% url 'team_fundraising:login' %}">Login</a>
                {% endif %}
            </div>
            </div>
        </nav>
    {% endblock navbar %}
    {% block body %}
        <div class="container">

            {% block content %}
            {% endblock content %}

        </div>
        <br/>
        <br/>

    {% endblock body %}

team_fundraising/templates/base_nonav.html
{% load static %}
<!doctype html>
<html lang="en">
    <head profile="https://www.w3.org/2005/10/profile">
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="icon" type="image/png" href="{% static "favicon.png" %}">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">        <link rel="stylesheet" href="{% static "fundraising.css" %}">
        <link rel="stylesheet" href="{% static "thermometer.css" %}">

        {% block head %}
        {% endblock head %}

    </head>
    <body>
        {% block navbar %}
        {% endblock navbar %}

        {% block body %}
        {% endblock body %}

    </body>
    </html>

team_fundraising/templates/index.html
{% extends "base_nonav.html" %}
{% load static %}
{% load humanize %}

{% block body %}
<br/>
<div class="container">
    <h4>Click on a campaign to get started:</h4>
    <br/>
    {% for campaign in active %}
    <div class="col-lg-8  mx-auto">
        <div class="card mb-3 text-center">
            <img class="card-img-top" src="{% static "homepage.jpg" %}" alt="Card image cap">
            <div class="card-body">
                <h2 class="card-title"><a class="stretched-link" href="{% url 'team_fundraising:index' campaign.id %}">{{ campaign.name }}</a></h2>
                <div class="progress" style="height: 25px;">
                    <div class="progress-bar bg-danger" role="progressbar" style="width: {% widthratio campaign.get_total_raised campaign.goal 100 %}%" aria-valuenow="{% widthratio campaign.get_total_raised campaign.goal 100 %}" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div>
                    Raised ${{ campaign.get_total_raised|floatformat:"0"|intcomma }} of
                    ${{ campaign.goal|floatformat:"0"|intcomma }}
                </div>
                <br/>
            </div>
        </div>
    </div>
{% endfor %}
</div>
<br/><br/>

<div class="container">
<center><h4>Previously finished campaigns</h4></center>
<br/>
{% for campaign in inactive %}
    <div class="col-lg-6  mx-auto">
        <div class="card mb-3 text-center">
            <img class="card-img-top" src="{% static "homepage.jpg" %}" alt="Card image cap">
            <div class="card-body">
                <h2 class="card-title"><a class="stretched-link" href="{% url 'team_fundraising:index' campaign.id %}">{{ campaign.name }}</a></h2>
                <div class="progress" style="height: 25px;">
                    <div class="progress-bar bg-danger" role="progressbar" style="width: {% widthratio campaign.get_total_raised campaign.goal 100 %}%" aria-valuenow="{% widthratio campaign.get_total_raised campaign.goal 100 %}" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <div>
                Raised ${{ campaign.get_total_raised|floatformat:"0"|intcomma }} of
                ${{ campaign.goal|floatformat:"0"|intcomma }}
                </div>
                <br/>
            </div>
        </div>
    </div>
{% endfor %}
</div>
{% endblock body %}