fundraiser/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.admin.views.decorators import staff_member_required
from .views import IndexView
from team_fundraising.admin import DonorCsv


urlpatterns = [
    path('', IndexView.as_view()),
    path('team_fundraising/', include('team_fundraising.urls')),

    # Donation reports in the admin section
    path(
        'admin/donation_report_csv/<int:campaign_id>/',
        staff_member_required(DonorCsv.as_view()),
        name="donation_report_csv"
    ),
    path('admin/', admin.site.urls),

    # Had to add accounts here as well, as internal functions call it without
    # a namespace
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

team_fundraising/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views
from .views import Paypal_donation, About, OneClickSignUp

app_name = 'team_fundraising'

urlpatterns = [
    path('', views.index_view_default, name='index_default'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('<campaign_id>/', views.index_view, name='index'),
    path(
        'fundraiser/<int:fundraiser_id>/',
        views.fundraiser_view,
        name='fundraiser'
    ),
    path('donation/<int:fundraiser_id>/', views.new_donation, name="donation"),
    path('paypal_donation/<int:fundraiser_id>/', Paypal_donation.as_view()),
    path(
        'accounts/update_fundraiser/',
        views.update_fundraiser,
        name="update_fundraiser",
    ),
    path(
        'accounts/update_fundraiser/<int:campaign_id>/',
        views.update_fundraiser,
        name="update_fundraiser",
    ),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/<int:campaign_id>/', views.signup, name="signup"),
    path(
        'accounts/signup_logged_in/<int:campaign_id>/',
        login_required(OneClickSignUp.as_view()),
        name="signup_logged_in"
    ),
    path(
        'accounts/change_password/',
        views.change_password,
        name='change_password'
    ),
    path('about/<int:campaign_id>/', About.as_view(), name="about"),
]

team_fundraising/models.py
""" Database models for the team_fundraising app

This module contains the models for the team_fundraising app, including a
parent Campaign, with individual Fundraisers, and Donations that can be raised
by the Fundraisers, or applied to the general Campaign.
"""
import os
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum, Count, Max, Q, F, FloatField, Case, When
from django.db.models.functions import Coalesce
from django.conf import settings
from PIL import Image


class Campaign(models.Model):
    """
    The parent object that defines the campaign to which all Fundraisers
    and Donations belong.
    """

    name = models.CharField(max_length=50)
    goal = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    campaign_message = models.TextField()
    default_fundraiser_message = models.TextField()
    default_fundraiser_amount = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def get_total_raised(self):
        """
        Get the total raised from all Fundraisers
        """

        # get all paid donations in this campaign for all fundraisers
        donations = Donation.objects.filter(
            fundraiser__campaign__pk=self.id,
            payment_status='paid'
        )

        # sum the amounts
        donations = donations.aggregate(
            total=Sum('amount', output_field=FloatField())
        )
        total_raised = donations['total']

        # replace with zero if there are none
        if total_raised is None:
            total_raised = 0

        # get the "general" donations, ones not to a fundraiser
        general_donations = Donation.objects.filter(
            pk=self.id, fundraiser__isnull=True
        )

        # add general donations to total
        for donation in general_donations:
            total_raised += donation.amount

        return total_raised

    def get_fundraisers_with_totals(self):
        """
        Get all fundraisers in this campaign, with their raised totals
        already included. This is designed to be more efficient (less queries)
        then running a total_raised() call on each fundraiser.
        """

        # sum the amount of only "paid" donations
        paid_donations = Coalesce(Sum(
            'donation__amount',
            filter=Q(donation__payment_status__exact='paid'),
            output_field=FloatField()
            ), 0, output_field=FloatField())

        # filter only fundraisers in this campaign
        fundraisers = Fundraiser.objects.filter(campaign_id=self.id)

        # create the annotated query
        fundraisers = fundraisers.annotate(
            total_raised=paid_donations
            )

        # sort by total raised
        fundraisers = fundraisers.order_by('-total_raised')

        return fundraisers

    def get_recent_donations(self, num_donations):

        # get z recent "paid" donations by newest date
        recent_donations = Donation.objects.filter(
            fundraiser__campaign__id=self.id,
            payment_status__in=["paid", ""]
        ).order_by('-date')[:num_donations]

        return recent_donations

    @staticmethod
    def get_latest_active_campaign():

        campaign = Campaign.objects.filter(
            active=True
        ).first()

        return campaign


class Fundraiser(models.Model):
    """
    An individual fundraiser that has a goal and collects donations to their
    total and the campaigns.
    """

    campaign = models.ForeignKey(Campaign, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, blank=True, null=True,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=50)
    goal = models.IntegerField(default=0, blank=True)
    photo = models.ImageField(upload_to='photos/', blank=True)
    photo_small = models.ImageField(upload_to='photos_small/', blank=True)
    message = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # Generate and save the lower-resolution version of the photo
        if self.photo:
            with Image.open(self.photo) as img:
                img.thumbnail((800, 800))
                photo_dir, photo_filename = os.path.split(self.photo.name)
                new_photo_path = os.path.join('photos_small', photo_filename)
                img.save(os.path.join(settings.MEDIA_ROOT, new_photo_path))
                self.photo_small.name = new_photo_path

        super().save(*args, **kwargs)

    def total_raised(self):
        """
        Get the sum of Donations for this Fundraiser
        """

        # get all paid donations for this fundraiser
        donations = Donation.objects.filter(
            fundraiser__pk=self.id,
            payment_status='paid'
        )

        # sum the donation amounts
        donations = donations.aggregate(total=Sum('amount'))

        # replace with 0 if there were none
        if donations["total"] is None:
            donations["total"] = 0

        return donations["total"]

    def total_donations(self):
        """
        Get the total number of donators for this Fundraiser
        """
        total_donations = 0

        # get all paid donations for this fundraiser
        donations = Donation.objects.filter(
            fundraiser__pk=self.id,
            payment_status='paid'
        )

        # sum the donation amounts
        total_donations = donations.aggregate(total=Count('amount'))

        return total_donations['total']

    @staticmethod
    def get_latest_active_campaign(user_id):
        """
        Given a user id, find the most recent active fundraiser
        """

        # pick an active campaign with the highest number
        fundraiser = Fundraiser.objects.filter(
            user=user_id,
        ).order_by('-campaign__active', '-campaign__id').first()

        return fundraiser


class Donation(models.Model):
    """
    Individual donations that are made to a fundraiser. Note there is no
    "Donater" object, as each donation is treated as unique.
    """

    fundraiser = models.ForeignKey(
        Fundraiser, blank=True, null=True,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=50)
    amount = models.FloatField(default=0)
    anonymous = models.BooleanField(default=False)
    email = models.EmailField()
    message = models.CharField(max_length=280, blank=True)
    tax_name = models.CharField(max_length=50, blank=True)
    address = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=50, blank=True)
    province = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=25, blank=True)
    postal_code = models.CharField(max_length=10, blank=True)
    date = models.DateTimeField(default=timezone.now)
    payment_method = models.CharField(max_length=50, blank=True)
    payment_status = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return self.name


class DonorManager(models.Manager):
    """
    A model query manager that combines all donation by the donor
    based on email, name and campaign
    """

    def get_queryset(self):

        donations = super(DonorManager, self).get_queryset()

        # get all donations by campaign
        # and have been fully paid through paypal
        donations = donations.filter(
            payment_status='paid'
            )

        # group by email address and the tax_name provided
        # fill in name with the tax_name, but fall back to name if it's blank
        donations = donations.values(
                    'email',
                    'tax_name',
                    campaign_id=F('fundraiser__campaign_id'),
                    #  sum values, name is the tax_name if it exists
                    #  otherwise the name
                    ).annotate(
                        name=Case(
                            When(tax_name='', then=F('name')),
                            default=F('tax_name'),
                            output_field=models.CharField(),
                            ),
                        amount=Sum('amount'),
                        num_donations=Count('email'),
                        address=Max('address'),
                        city=Max('city'),
                        province=Max('province'),
                        postal_code=Max('postal_code'),
                        country=Max('country'),
                        date=Max('date'),
                    )

        return donations


class Donor(Donation):
    """
    A proxy model of the Donation model, used to summarize all the
    Donations by person, for reporting purposes.
    """

    objects = DonorManager()

    class Meta:
        proxy = True
        verbose_name = 'Donor'


class ProxyUser(User):
    """
    A proxy mode of the User model, to provide additional functions
    for the User
    """

    class Meta:
        proxy = True
        verbose_name = 'UserProxy'

    def get_latest_fundraiser(self):
        """
        Get a single, latest fundraiser for the user.
        For now, uses id order to identify the latest one.
        """

        fundraiser = Fundraiser.objects.filter(
            user_id=self.id
        ).order_by('id').first()

        return fundraiser

team_fundraising/forms.py
""" The forms for the team_fundraiser app
"""
from django import forms
from django.utils import timezone
from .models import Fundraiser
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class DonationForm(forms.Form):
    """ Form for a new Donation, which can be tied to a specific fundraiser """

    name = forms.CharField()
    amount = forms.CharField()
    other_amount = forms.CharField(required=False)
    email = forms.EmailField()
    anonymous = forms.BooleanField(required=False)
    tax_name = forms.CharField(label='Full Name', required=False)
    address = forms.CharField(max_length=100, required=False)
    city = forms.CharField(max_length=50, required=False)
    province = forms.CharField(max_length=50, required=False)
    country = forms.CharField(max_length=25, required=False)
    postal_code = forms.CharField(max_length=10, required=False)
    date = timezone.now()

    message = forms.CharField(
        widget=forms.Textarea(
            attrs={'required': False, 'rows': 3}
        ),
        required=False
    )

    def clean(self):
        # if the user chooses "other amount", make that the amount

        cleaned_data = super().clean()

        try:
            amount = cleaned_data.get("amount")
        except KeyError:
            amount = ""

        try:
            other_amount = cleaned_data.get("other_amount")
        except KeyError:
            other_amount = ""

        if amount == 'other' or amount == '':
            # TODO pull out just the number, in case they added a $
            try:
                cleaned_data['amount'] = float(other_amount)
            except ValueError:
                raise forms.ValidationError("Amount is not a number")

        return cleaned_data


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)


class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')

    def __init__(self, *args, **kwargs):

        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs.pop("autofocus", None)

        self.fields['email'].required = True
        self.fields['username'].required = True

        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.username = self.cleaned_data["username"]
        user.email = self.cleaned_data["email"]
        user.is_staff = False
        user.is_admin = False

        if commit:
            user.save()

        return user


class FundraiserForm(forms.ModelForm):
    class Meta:
        model = Fundraiser
        fields = ('campaign', 'name', 'goal', 'photo', 'message')
        widgets = {
            'campaign': forms.HiddenInput(),
            'message': forms.Textarea(attrs={'rows': 3, 'cols': 20}),
        }

    def __init__(self, *args, **kwargs):
        super(FundraiserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['name'].widget.attrs['size'] = 50
        self.fields['goal'].widget.attrs['size'] = 10

        self.fields['name'].required = True
        self.fields['goal'].required = True

        # disable all the fields if the campaign is no longer active
        if self.instance.pk is not None:

            if self.instance.campaign.active is False:

                for field in self.fields:
                    self.fields[field].disabled = True

fundraiser/views.py
from django.shortcuts import render
from django.views import View
from team_fundraising.models import Campaign


class IndexView(View):
    # Show the list of active and inactive campaigns

    def get(self, request):

        active = Campaign.objects.filter(active=True)
        inactive = Campaign.objects.filter(active=False)
        template = 'index.html'

        context = {
            'active': active,
            'inactive': inactive,
        }

        return render(request, template, context)

team_fundraising/templates/team_fundraising/donation.html
{% extends "base.html" %}
{% block head %}
<title>Donate to {{ fundraiser.name }}</title>
{% endblock head %}
{% block content %}

{% load crispy_forms_tags %}
<br/>
<h3>Donate to {{ fundraiser.name }}'s fundraising</h3>
<br/>
<form method="post">
    {% csrf_token %}

    {# show form errors at the top of the page #}
    {% if form.errors %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}

    <div id="div_id_amount" class="form-group">
        <label for="id_amount" class="col-form-label  requiredField">
            Amount<span class="asteriskField">*</span>
        </label>
        <div>
            <input type="radio" class="radio" id="id_amount" name="amount" value="10">
            <label for="10">$10</label>
        </div>
        <div>
            <input type="radio" class="radio" id="id_amount" name="amount" value="25">
            <label for="25">$25</label>
        </div>
        <div>
            <input type="radio" class="radio" id="id_amount" name="amount" value="50">
            <label for="50">$50</label>
        </div>
        <div>
            <input type="radio" class="radio" id="id_amount" name="amount" value="100">
            <label for="100">$100</label>
        </div>
        <div>
            <input type="radio" class="radio" id="other" name="amount" value="other">
            <label for="other" class="col-form-label">Other:</label>
            <div class="input-group">
                <div class="input-group-prepend">
                  <span class="input-group-text" id="inputGroupPrepend">$</span>
                </div>
                <input type="number" min="0" step="0.01" class="form-control" id="other" name="other_amount" size="10" onclick="document.getElementById('other').checked = true;">
            </div>
        </div>
        <div>
            Donation are allocated to our charities where funds are of immediate priority
        </div>
    </div>

    <div>
        {{ form.name|as_crispy_field }}
    </div>
    <div class="form-group">
        <div id="div_id_anonymous" class="form-check">
            <label for="id_anonymous" class="form-check-label">
                <input type="checkbox" name="anonymous" class="checkboxinput form-check-input" id="id_anonymous">
                Anonymous (your name will not appear on the site)
            </label>
        </div>
    </div>
    <div>
        {{ form.email|as_crispy_field }}
    </div>
    <div>
        <div id="div_id_message" class="form-group">
                <label for="id_message" class="col-form-label ">
                    Message (This will appear along with your donation)
                </label>
                <div class="">
                        <textarea name="message" cols="40" rows="3" class="textarea form-control" id="id_message"></textarea>
                </div>
        </div>
    </div>
    <hr>
    <div>Please fill in the following information to receive a tax receipt for donations over $20:</div>
    <br>
    <div>
        {{ form.tax_name|as_crispy_field }}
    </div>
    <div>
        {{ form.address|as_crispy_field }}
    </div>
    <div>
        {{ form.city|as_crispy_field }}
    </div>
    <div>
        {{ form.province|as_crispy_field }}
    </div>
    <div>
        {{ form.country|as_crispy_field }}
    </div>
    <div>
        {{ form.postal_code|as_crispy_field }}
    </div>
    </br>
    <div>
        <input type="submit" class="btn btn-primary" value="Donate now">
    </div>
</form>
{% endblock content %}

team_fundraising/templates/team_fundraising/fundraiser.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}

{% block head %}
<title>{{ fundraiser.name }}'s Fundraising Page </title>
<meta property="og:url"         content="{{ request.build_absolute_uri }}" />
<meta property="og:title"       content="Triple Crown for Heart Fundraising" />
<meta property="og:description" content="I'm fundraising for the Triple Crown for Heart, raising money for the BC Children's Hospital and the Children's Heart Network." />
<meta property="og:type" content="website" />
<meta property="og:image" content="https://{{ request.META.HTTP_HOST }}{% static "nophoto.png" %}" />
<meta property="fb:app_id" content="903165813185691" />

{% endblock head %}

{% block content %}
{% for message in messages %}

    <div class="alert alert-primary" role="alert">
        {{ message }}
    </div>

    {% endfor %}
    <br/>

    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                {% if fundraiser.photo_small %}
                    <img src="{{ fundraiser.photo_small.url }}" width="200" height="200" class="circle-image">
                {% elif fundraiser.photo %}
                    <img src="{{ fundraiser.photo.url }}" width="200" height="200" class="circle-image">
                {% else %}
                    <img  src="{% static "nophoto.png" %}" alt="Card image cap" width="200" height="200" class="circle-image">
                {% endif %}

                <h2>{{ fundraiser.name }}</h2>
            </div>
            <div class="col-lg-6">

                <div id="countdown-wrap">
                <div id="goal-stat">
                    <div id="raised"><strong>${{ fundraiser.total_raised|floatformat:"0"|intcomma }}</strong></div>
                    <div id="goal">Goal: ${{ fundraiser.goal|floatformat:"0"|intcomma }}</div>
                </div>
                <div id="glass">
                    <div id="progress">
                    </div>
                </div>
                <div class="goal-stat">
                    <span class="goal-number">{{ fundraiser.percent_raised|floatformat:"0" }}%</span>
                </div>
                </div>
                <script>
                    document.getElementById("progress").style.width = "{{ fundraiser.percent_raised }}%";
                </script>

                <!--https://stackoverflow.com/questions/9335140/how-to-countdown-to-a-date -->


                <a class="btn btn-primary donate-button" href="{% url 'team_fundraising:donation' fundraiser.id %}" role="button">Donate</a>
                <br/>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <br/>
                {{ fundraiser.message|safe }}
                {% if user.is_authenticated and user.id == fundraiser.user.id  %}
                    <br/>
                    <a class="btn btn-secondary" href="{% url 'team_fundraising:update_fundraiser' fundraiser.campaign.id %}" role="button">Edit</a>
                {% endif %}
            </div>
            <div class="col-lg-6">
                <h4>Recent Donations</h4>
                {{ fundraiser.Donation }}
                <ul>
                    {% for donation in donations %}
                    <li>
                            {% if  donation.anonymous %}
                                Anonymous
                            {% else %}
                                {{ donation.name }}
                            {% endif %}
                            - ${{ donation.amount|floatformat:"2"|intcomma }}
                            {% if donation.message %}
                            - {{ donation.message }}
                            {% endif %}
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
   {% endblock %}

team_fundraising/templates/team_fundraising/index.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block head %}
<title>Fundraising</title>
<script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
{% endblock head %}

{% block content %}
{% for message in messages %}

  <div class="alert alert-primary" role="alert">
      {{ message }}
  </div>

  {% endfor %}
  <div class="row">
    <div class="col-lg-6">
      <br/>
      <h3>{{ campaign.name }}</h3>
      <img src="{% static "homepage.jpg" %}" width="100%">
      <div id="countdown-wrap">
        <div id="goal-stat">
          <div id="raised"><strong>${{ total_raised|floatformat:"0"|intcomma }}</strong></div>
          <div id="goal">Goal: ${{ campaign.goal|floatformat:"0"|intcomma }}</div>
        </div>
        <div id="glass">
          <div id="progress">
          </div>
        </div>
        <div class="goal-stat">
          <span class="goal-number">{% widthratio total_raised campaign.goal 100 %}%</span>
        </div>
      </div>
      {{ campaign.campaign_message|safe }}
      <br/><br/>
      <div>
        <h4>Recent Donations</h4>
        {% for donation in recent_donations %}
          {% if  donation.anonymous %}
            Anonymous
          {% else %}
            {{ donation.name }}
          {% endif %}
          donated ${{ donation.amount|floatformat:"2"|intcomma }} to {{donation.fundraiser.name }}<br/>
        {% endfor %}
      </div>
      <script>
        document.getElementById("progress").style.width = "{% widthratio total_raised campaign.goal 100 %}%";
      </script>
    </div>
    <div class="col-lg-6">
      <br/>
      {% if user.is_authenticated %}
        <a class="btn btn-secondary secondary-button" href="{% url 'team_fundraising:update_fundraiser' campaign.id %}">Edit my profile</a>
      {% else %}
        <a class="btn btn-secondary secondary-button" href="{% url 'team_fundraising:signup' campaign.id %}">Create a fundraiser page</a>
      {% endif %}      <br/>

      <div>
      <!-- Search form --></form>
      <form class="form-inline">
              <input id="search" class="form-control form-control-md ml-3 full-width"
                type="text" placeholder="Search for a fundraiser" data-search />
      </form>
      </div>
    <br/>
    <div class="d-flex flex-wrap justify-content-around">

          {% for fundraiser in fundraisers %}
              <div class="card mt-3 mr-1" style="width: 160px;" data-filter-item data-filter-name="{{ fundraiser.name|lower }}">
                {% if fundraiser.photo_small %}
                  <img class="card-img-top circle-image-small" src="{{ fundraiser.photo_small.url }}" alt="Card image cap" width="140" height="140">
                {% elif fundraiser.photo %}
                  <img class="card-img-top circle-image-small" src="{{ fundraiser.photo.url }}" alt="Card image cap" width="140" height="140">
                {% else %}
                  <img class="card-img-top circle-image-small" src="{% static "nophoto.png" %}" alt="Card image cap" width="140" height="140">
                {% endif %}
                <div class="card-body">
                  <p class="card-title">
                      {{ fundraiser.name }}</p>
                  <p class="card-text">
                      ${{ fundraiser.total_raised|floatformat:"0"|intcomma }}
                      of ${{ fundraiser.goal|floatformat:"0"|intcomma }}</p>
                  <a href="{% url 'team_fundraising:fundraiser' fundraiser.id %}" class="stretched-link"></a>
                </div>
              </div>
          {% endfor %}
        </div>

      <br/>
    </div>
  </div>

<script>
/*
  https://codepen.io/alexerlandsson

	How to use:
	1)	Copy this jQuery to your project
	2)	Add [data-search] to search input
	3)	Add [data-filter-item] to the items that should be filtered
	4)	Add [data-filter-name="SEARCH TERM"] to the filter-items

*/

$('[data-search]').on('keyup', function() {
	var searchVal = $(this).val();
	var filterItems = $('[data-filter-item]');

	if ( searchVal != '' ) {
		filterItems.addClass('hidden');
		$('[data-filter-item][data-filter-name*="' + searchVal.toLowerCase() + '"]').removeClass('hidden');
	} else {
		filterItems.removeClass('hidden');
	}
});
</script>

{% endblock %}

team_fundraising/templates/team_fundraising/paypal_donation.html
{% extends "base.html" %}
{% load humanize %}
{% block head %}
<title>Confirmation</title>
{% endblock head %}
{% block content %}

Please confirm your information:

<br/><br/>
<table class="table">
    <tr>
        <td>Name:</td>
        <td>{{ donation.name }}</td>
    </tr>
    <tr>
        <td>Amount:</td>
        <td>${{ donation.amount|floatformat:"2"|intcomma }}</td>
    </tr>
    <tr>
        <td>Email:</td>
        <td> {{ donation.email }}</td>
    </tr>
    <tr>
        <td>Message:</td>
        <td>{{ donation.message }}</td>
    </tr>
</table>

<br/>
You will be redirected to Paypal to complete the payment.<br/>
You can choose "Pay with a credit or Visa Debit card" at the bottom if you don't have a Paypal account.
<br/><br/>
<!-- writes out the form tag automatically -->
{{ form.render }}
{% endblock content %}

team_fundraising/templates/team_fundraising/update_fundraiser.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<title>Update your fundraising page</title>
<script src="//cdn.ckeditor.com/4.11.4/basic/ckeditor.js"></script>
{% endblock head %}

{% block content %}
{% for message in messages %}

    <div class="alert alert-primary" role="alert">
        {{ message }}
    </div>

{% endfor %}
<br/>
<h3>{{ campaign.name }}</h3>
{%  if not campaign.active %}

    <div class="alert alert-warning" role="alert">
      This campaign is no longer active.

      {% if active_campaign.id == latest_fundraiser.campaign.id %}

        You probably want to edit the new campaign:
          <a href="{% url 'team_fundraising:update_fundraiser' latest_fundraiser.campaign.id %}">
            {{ latest_fundraiser.campaign.name }}</a>

      {% else %}

          Please join the new campaign:
          <a href="{% url 'team_fundraising:signup' active_campaign.id %}">
            {{ active_campaign.name }}
          </a>

      {% endif %}
      <br>
      If you need to change something in this campaign, please contact the organization directly.

    </div>
{%  endif %}

{% if active_campaign.id != latest_fundraiser.campaign.id %}
  <a class="btn btn-primary primary-button" href="{% url 'team_fundraising:signup_logged_in' active_campaign.id %}">Join the new campaign</a>
  <br/><br/>
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ fundraiser_form|crispy }}
    {{ user_form|crispy }}
    <a class="float-right" href="{% url 'team_fundraising:change_password' %}">Change Password</a>
    <br/>

    {% if campaign.active %}
      <button class="btn btn-primary" type="submit"> Save Changes</button>
    {% endif %}

    <script>
        CKEDITOR.replace( 'message', {
        height: 260,
      /* Default CKEditor styles are included as well to avoid copying default styles. */
      contentsCss: [
        'https://cdn.ckeditor.com/4.11.4/full-all/contents.css',
        '{% static "ck_editor_override.css  " %}'
      ]
    } );
    </script>
</form>

{% endblock content %}